### ISSUE TITLE
Exit on fatal errors?

### ISSUE THREAD

**Issue by yields** [segment-boneyard/herd#10]
@calvinfo thoughts?

```
info - Connecting to mongo .. - {"uri":"mongodb://localhost:27017/segmentio"}
error - Error connecting to mongo! - {"err":{},"options":"mongodb://localhost:27017/segmentio"}
critical - cannot connect to mongo - {"message":"failed to connect to [localhost:27017]","stack":"Error: failed to connect to [localhost:27017]\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)\n    at emit (events.js:106:17)\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)\n    at emit (events.js:98:17)\n    at Socket.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)\n    at Socket.emit (events.js:95:17)\n    at net.js:441:14\n    at process._tickCallback (node.js:448:13)"}
  herd The worker exited incorrectly. code: 1 +580ms
  herd spawned new worker 62 +0ms
info - Connecting to mongo .. - {"uri":"mongodb://localhost:27017/segmentio"}
error - Error connecting to mongo! - {"err":{},"options":"mongodb://localhost:27017/segmentio"}
critical - cannot connect to mongo - {"message":"failed to connect to [localhost:27017]","stack":"Error: failed to connect to [localhost:27017]\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)\n    at emit (events.js:106:17)\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)\n    at emit (events.js:98:17)\n    at Socket.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)\n    at Socket.emit (events.js:95:17)\n    at net.js:441:14\n    at process._tickCallback (node.js:448:13)"}
  herd The worker exited incorrectly. code: 1 +580ms
  herd spawned new worker 63 +0ms
info - Connecting to mongo .. - {"uri":"mongodb://localhost:27017/segmentio"}
error - Error connecting to mongo! - {"err":{},"options":"mongodb://localhost:27017/segmentio"}
critical - cannot connect to mongo - {"message":"failed to connect to [localhost:27017]","stack":"Error: failed to connect to [localhost:27017]\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)\n    at emit (events.js:106:17)\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)\n    at emit (events.js:98:17)\n    at Socket.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)\n    at Socket.emit (events.js:95:17)\n    at net.js:441:14\n    at process._tickCallback (node.js:448:13)"}
  herd The worker exited incorrectly. code: 1 +560ms
  herd spawned new worker 64 +0ms
info - Connecting to mongo .. - {"uri":"mongodb://localhost:27017/segmentio"}
error - Error connecting to mongo! - {"err":{},"options":"mongodb://localhost:27017/segmentio"}
critical - cannot connect to mongo - {"message":"failed to connect to [localhost:27017]","stack":"Error: failed to connect to [localhost:27017]\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)\n    at emit (events.js:106:17)\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)\n    at emit (events.js:98:17)\n    at Socket.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)\n    at Socket.emit (events.js:95:17)\n    at net.js:441:14\n    at process._tickCallback (node.js:448:13)"}
  herd The worker exited incorrectly. code: 1 +580ms
  herd spawned new worker 65 +0ms
info - Connecting to mongo .. - {"uri":"mongodb://localhost:27017/segmentio"}
error - Error connecting to mongo! - {"err":{},"options":"mongodb://localhost:27017/segmentio"}
critical - cannot connect to mongo - {"message":"failed to connect to [localhost:27017]","stack":"Error: failed to connect to [localhost:27017]\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)\n    at emit (events.js:106:17)\n    at null.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)\n    at emit (events.js:98:17)\n    at Socket.<anonymous> (/src/node_modules/@segment/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)\n    at Socket.emit (events.js:95:17)\n    at net.js:441:14\n    at process._tickCallback (node.js:448:13)"}
  herd The worker exited incorrectly. code: 1 +570ms
  herd spawned new worker 66 +0ms
```

**Comment by calvinfo** [comment]
Hmm yeah, maybe we should after a certain threshold. 

Slightly related, but we can just remove herd from CDN.

**Comment by yields** [comment]
ah cool, removing it then.
